// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package game_record

import (
	"zjsj/api/game_record"
)

type ControllerAdmin struct{}

func NewAdmin() game_record.IGameRecordAdmin {
	return &ControllerAdmin{}
}
