# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "mysql:root:ycsjgame2026root@tcp(127.0.0.1:33060)/hxnc?charset=utf8mb4&collation=utf8mb4_unicode_ci&loc=Local&parseTime=true"
        descriptionTag: true
        tables: "users,game_records,glasses,glasses_uses"

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app

  build:
    name: "main"
    arch: "amd64"
    system: "linux"
    mod: "none"
    packSrc: "resource,manifest"
    version: "v1.0.0"
    output: "./out/main"
    cgo: 0
    extra: ""
    dumpEnv: false
