// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"zjsj/internal/dao/internal"
)

// gameRecordsDao is the data access object for the table game_records.
// You can define custom methods on it to extend its functionality as needed.
type gameRecordsDao struct {
	*internal.GameRecordsDao
}

var (
	// GameRecords is a globally accessible object for table game_records operations.
	GameRecords = gameRecordsDao{internal.NewGameRecordsDao()}
)

// Add your custom methods and functionality below.
