// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"zjsj/internal/dao/internal"
)

// gameStartRecordsDao is the data access object for the table game_start_records.
// You can define custom methods on it to extend its functionality as needed.
type gameStartRecordsDao struct {
	*internal.GameStartRecordsDao
}

var (
	// GameStartRecords is a globally accessible object for table game_start_records operations.
	GameStartRecords = gameStartRecordsDao{internal.NewGameStartRecordsDao()}
)

// Add your custom methods and functionality below.
