// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"zjsj/internal/dao/internal"
)

// glassesDao is the data access object for the table glasses.
// You can define custom methods on it to extend its functionality as needed.
type glassesDao struct {
	*internal.GlassesDao
}

var (
	// Glasses is a globally accessible object for table glasses operations.
	Glasses = glassesDao{internal.NewGlassesDao()}
)

// Add your custom methods and functionality below.
