// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"zjsj/internal/dao/internal"
)

// glassesUsesDao is the data access object for the table glasses_uses.
// You can define custom methods on it to extend its functionality as needed.
type glassesUsesDao struct {
	*internal.GlassesUsesDao
}

var (
	// GlassesUses is a globally accessible object for table glasses_uses operations.
	GlassesUses = glassesUsesDao{internal.NewGlassesUsesDao()}
)

// Add your custom methods and functionality below.
