// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package glasses

import (
	"zjsj/api/glasses"
)

type ControllerApi struct{}

func NewApi() glasses.IGlassesApi {
	return &ControllerApi{}
}
