// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package glasses_use

import (
	"zjsj/api/glasses_use"
)

type ControllerApi struct{}

func NewApi() glasses_use.IGlassesUseApi {
	return &ControllerApi{}
}
